set shell := ["fish", "-c"]

default:
    @just -g --list

sync:
    @echo "syncing"
    
git_update dir:
    z {{dir}}
    set curdate (date "+%d/%m/%y")
    git add . && git commit -m "update: $curdate" && git push
    z -
    
