formulae = [
  "bat",
  "btop",
  "elixir",
  "eza",
  "fd",
  "ffmpeg",
  "fish",
  "fourmolu",
  "fzf",
  "gh",
  "ghcup",
  "helix",
  "hgrep",
  "neovim",
  "odin",
  "raylib",
  "ripgrep",
  "rust",
  "stylua",
  "taplo",
  "tree-sitter",
  "wget",
  "yazi",
  "zoxide",
]
casks = [
  "antinote",
  "font-iosevka-nerd-font",
  "ghostty",
  "iina",
  "keycastr",
  "raycast",
  "zen-browser",
]
