[server]
browser = "default"
follow_symlink = false

[runtime]
auto_instantiate = true
output_max_bytes = 8000000
watcher_on_save = "lazy"
on_cell_change = "autorun"
pythonpath = []
auto_reload = "off"
std_stream_max_bytes = 1000000

[keymap]
preset = "vim"
[keymap.overrides]
"cell.focusUp" = "Ctrl-Shift-k"
"cell.focusDown" = "Ctrl-Shift-j"
"global.toggleSidebar" = "Ctrl-Shift-h"
"completion.moveDown" = "Ctrl-j"
"completion.moveUp" = "Ctrl-k"
"cell.createBelow" = "Ctrl-Shift-p"
"cell.createAbove" = "Ctrl-Shift-o"

[formatting]
line_length = 79

[snippets]
include_default_snippets = true
custom_paths = []

[display]
theme = "dark"
cell_output = "above"
code_editor_font_size = 14
default_width = "compact"
dataframes = "rich"

[experimental]
rtc = false
multi_column = true
chat_sidebar = true
tracing = true

[ai]
rules = "- prefer polars over pandas\n- make charts using altair"
[ai.google]

[ai.open_ai]
api_key = "ollama"
model = "qwen2.5:0.5b"
base_url = "http://127.0.0.1:11434/v1"

[ai.anthropic]

[package_management]
add_script_metadata = true
manager = "uv"

[completion]
copilot = false
activate_on_typing = true

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = true
